#ifndef Bezier_HPP
#define Bezier_HPP
/// bezier curve generated by De Casteljau's algorithm

class  Bezier final : public IShape
{
private:
	vec2_t&& deCasteljau( float dt) const;
	std::vector<vec2_t> draw_bezier()const;

public:

  void draw(const IContext2D* ctx) const override;
  
  std::vector<vec2_t> control_points;
  int precision{0};
  ~Bezier() override;
};
#endif